spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: vit
    password: vit
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:postgresql://localhost:5432/vit
#    username: postgres
#    password: oracle
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
      dialect: org.hibernate.dialect.Oracle12cDialect
      database-platform: org.hibernate.dialect.Oracle12cDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    whitelabel:
      enabled: false
#  port: 8081
jwt:
  secret: fff123

